# Generated by Django 5.2.10 on 2026-02-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='parent',
        ),
    ]
