# Generated by Django 5.2.10 on 2026-02-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_reservedproduct'),
        ('orders', '0004_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_products', to='orders.order'),
        ),
    ]
