# Generated by Django 5.2.10 on 2026-02-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_snapshot',
            field=models.TextField(blank=True, help_text='Endereço no momento da compra'),
        ),
    ]
