# Generated by Django 5.2.10 on 2026-02-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_snapshot',
            field=models.TextField(blank=True, help_text='Snapshot of the address at the time of order'),
        ),
    ]
